- name: Crear múltiples aliases llamando playbook individual
  hosts: localhost
  gather_facts: no
  vars_files:
    - aliases.yml
  #  Formato esperado del archivo de alias
  #  aliases:
  #    - name:   AIX72_ORCLX_DESA_v1_fcs4   
  #      wwn:    c0:50:76:0a:43:62:00:b2
  #    - name:   AIX72_ORCLX_DESA_v2_fcs4   
  #      wwn:    c0:50:76:0a:43:62:00:b4

  tasks:
  
    # filtro el archivo de entrada para evitar duplicados 
    - name: Filtrar aliases únicos por nombre
      set_fact:
        aliases_unicos: "{{ aliases | unique(attribute='name') }}"
    
    # consulto al SW el listado de alias configurados
    - name: Obtener aliases existentes
      raw: aliasshow
      register: aliases_actuales_raw

    # extraer nombres de alias existentes
    - name: Crear múltiples aliases llamando playbook individual
  hosts: localhost
  gather_facts: no
  vars_files:
    - aliases.yml
  #  Formato esperado del archivo de alias
  #  aliases:
  #    - name:   AIX72_ORCLX_DESA_v1_fcs4   
  #      wwn:    c0:50:76:0a:43:62:00:b2
  #    - name:   AIX72_ORCLX_DESA_v2_fcs4   
  #      wwn:    c0:50:76:0a:43:62:00:b4

  tasks:
  
    # filtro el archivo de entrada para evitar duplicados 
    - name: Filtrar aliases únicos por nombre
      set_fact:
        aliases_unicos: "{{ aliases | unique(attribute='name') }}"
    
    # consulto al SW el listado de alias configurados
    - name: Obtener aliases existentes
      raw: aliasshow
      register: aliases_actuales_raw

    # lista de nombre de alias que ya existen en el SW
    - name: Extraer nombres de alias existentes
      set_fact:
        aliases_actuales: "{{ aliases_actuales_raw.stdout_lines | map('regex_search', '^Alias name: (.+)$') | select('string') | list }}"

    # listado de entrada in duplicados y son los que y existen  
    - name: Filtrar aliases que no existen en el switch
      set_fact:
        aliases_para_crear: "{{ aliases_unicos | rejectattr('name', 'in', aliases_actuales) | list }}"

    # llamar al playbook qeu crea el alias
    - name: Crear aliases uno por uno
      ansible.builtin.include_playbook:
        file: crear_alias.yml
      vars:
        alias_name: "{{ item.name }}"
        alias_wwn: "{{ item.wwn }}"
      loop: "{{ aliases }}"
      when: item.name not in aliases_para_crear
    
      
    - name: Procesar salida para extraer nombres de alias
      set_fact:
        aliases_actuales: "{{ aliases_actuales_raw.stdout_lines | map('regex_search', '^Alias name: (.+)$') | select('string') | list }}"
    
    - name: Crear aliases uno por uno
      ansible.builtin.include_playbook:
        file: crear_alias.yml
      vars:
        alias_name: "{{ item.name }}"
        alias_wwn: "{{ item.wwn }}"
      loop: "{{ aliases }}"
      when: item.name not in aliases_actuales
