- name: Crear múltiples aliases llamando playbook individual
  hosts: localhost
  gather_facts: no
  vars_files:
    - aliases.yml
    
  tasks:
  
    # filtro el archivo de entrada para evitar duplicados 
    - name: Filtrar aliases únicos por nombre
      set_fact:
        aliases_unicos: "{{ aliases | unique(attribute='name') }}"
    
    # llamar al playbook qeu crea el alias
    - name: Crear aliases uno por uno
      ansible.builtin.include_playbook:
        file: crear_alias.yml
      vars:
        alias_name: "{{ item.name }}"
        alias_wwn: "{{ item.wwn }}"
      loop: "{{ aliases }}"
      when: item.name not in aliases_para_crear
          
