- name: Crear zonas iniciales y configurar SAN
  hosts: brocade_switches
  gather_facts: no
  vars_files:
     - zonas.yml
  vars:
    config_nombre: mi_config

  tasks:
    - name: Agregar la clave del host a Known_hosts
        shell: ssh-keyscan -H {{ ansible_hosts }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      
    - name: Crear zonas iniciales
      raw: >
        zonecreate {{ item.name }},{{ item.members | join(';') }}
      loop: "{{ zones }}"
      ignore_errors: yes

    - name: Crear configuración
      raw: cfgcreate {{ config_nombre }}
      ignore_errors: yes

    - name: Agregar zonas a configuración
      raw: cfgadd {{ config_nombre }},{{ item.name }}
      loop: "{{ zones }}"

    - name: Activar configuración
      raw: cfgenable {{ config_nombre }}
