---
- name: Configure DNS servers
  hosts: localhost
  gather_facts: false
  collections:
    - brocade.fos
  vars:
    credential:
      fos_ip_addr: "{{ inventory_hostname }}"
      fos_user_name: admin
      fos_password: "TuPassword"
      https: false
  tasks:
    - name: deshabilitar SW
      brocade_fibrechannel_switch:
        credential: "{{ credential }}"
        vfid: -1
        switch:
          enabled_state: False 
    - name: Agregar DNS servers
      brocade_fibrechannel_switch:
        credential: "{{ credential }}"
        vfid: -1
        switch:
          dns_servers:
            dns_server:
              - "8.8.8.8"
              - "8.8.4.4"
    - name: hbilitar sw
      brocade_fibrechannel_switch:
        credential: "{{ credential }}"
        vfid: -1
        switch:
          enabled_state: True
