- name: Configurar servidores DNS en Brocade G720
  hosts: all
  gather_facts: no
  vars:
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"

  tasks:

    # - name: Agregar la clave del host a Known_hosts
    #   shell: ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts
    #   delegate_to: localhost

    - name: Asegurar que la IP esté en known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
        path: "~/.ssh/known_hosts"
      delegate_to: localhost

    - name: Agregar servidores DNS
      raw: dnsconfig --add {{ item }}
      loop: "{{ dns_servers }}"
      register: dns_add_result
      changed_when: fals
      failed_when: false

    - name: Mostrar salida (opcional)
      debug:
        var: dns_add_result.results

