- name: Crear múltiples aliases en Brocade G720
  hosts: all
  gather_facts: no
  vars_files:
    - ./datos/alias_new.yml  # Archivo con la lista de aliases

  tasks:

    # - name: Agregar la clave del host a Known_hosts
    #   shell: ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts
    #   delegate_to: localhost

    - name: Asegurar que la IP esté en known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
        path: "~/.ssh/known_hosts"
      delegate_to: localhost

    - name: Filtrar aliases únicos por nombre
      set_fact:
        aliases_unicos: "{{ aliases | unique(attribute='name') }}"
        
    - name: Agregar clave SSH a known_hosts (si no está)
      shell: ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      ignore_errors: yes

    - name: Crear alias en el switch uno por uno
      loop: "{{ aliases_unicos }}"
      loop_control:
        label: "{{ item.name }}"
      block:

        - name: Ejecutar alicreate con raw
          raw: alicreate {{ item.name }},{{ item.wwn }}
          register: result
          failed_when: false  

        - name: Mostrar resultado
          debug:
            msg: "Alias {{ item.name }} creado: {{ result.stdout }}"
      
      rescue:
        - name: Avisar si hubo error creando el alias
          debug:
            msg: "Hubo un error al crear el alias {{ item.name }} — Continuando..."
