- name: Crear configuración y zonas en Brocade G720
  hosts: all
  gather_facts: no

  vars:
    config_name: FABRIC_D
  
  vars_files:
    - ./datos/zones_new.yml

  tasks:

    # - name: Agregar la clave del host a Known_hosts
    #   shell: ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts
    #   delegate_to: localhost

    - name: Asegurar que la IP esté en known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
        path: "~/.ssh/known_hosts"
      delegate_to: localhost

    - name: Crear cada zona con sus miembros 
      loop: "{{ zones }}"
      loop_control:
        label: "{{ item.name }}"
      block:
        - name: Crear zona
          raw: >
            zonecreate {{ item.name }},{{ item.members | join(',') }}
          register: zonecreate_result
          failed_when: false

        - name: Mostrar resultado de creación zona
          debug:
            msg: "Zona {{ item.name }}: {{ zonecreate_result.stdout }}"

    - name: Crear configuración cfg1 con todas las zonas
      raw: >
        cfgcreate  {{ config_name }},{{ zones | map(attribute='name') | join(',') }}
      register: cfgcreate_result
      failed_when: false
      changed_when: false

    - name: Guardar configuración
      raw: cfgsave
      register: cfgsave_result
      failed_when: false

    - name: Activar configuración cfg1
      raw: cfgenable "cfg1"
      register: cfgenable_result
