- name: Configurar servidor NTP en Brocade G720
  hosts: all
  gather_facts: no
  vars:
    ntp_servers: 
      - "10.82.8.110"  # Reemplazar por la ip de tu servidor
      - "10.82.8.111"  # Reemplazar por la ip de tu servidor
    timezone: "America/Asuncion"  # Cambiá esto por la zona que necesites (ver lista con tsTimeZone --list) America/Argentina/Buenos_Aires

  tasks:

    # - name: Agregar la clave del host a Known_hosts
    #   shell: ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts
    #   delegate_to: localhost

    - name: Asegurar que la IP esté en known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
        path: "~/.ssh/known_hosts"
      delegate_to: localhost
    
    - name: Configurar servidor NTP con sclockserver
      raw: sclockserver {{ item }}
      loop: "{{ ntp_servers }}"
      failed_when: false
      register: ntp_output

    - name: Mostrar salida
      ansible.builtin.debug:
        var: ntp_output.results

    - name: Configurar zona horaria con tsTimeZone
      raw: tsTimeZone {{ timezone }}
      register: timezone_output
      failed_when: false
      
    - name: Mostrar salida (opcional)
      ansible.builtin.debug:
        var: timezone_output.stdout
