---
- name: Configuracion servicio NTP (local)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - brocade.fos
  vars:
    credential:
      fos_ip_addr: 10.82.1.90
      fos_user_name: admin
      fos_password: passw0rd
      https: False
  tasks:
  - name: configuracion ntp server
    brocade_time_clock_server:
      credential: "{{credential}}"
      vfid: -1
      clock_server:
        ntp_server_address:
          server_address:
            - "10.38.2.80"
            - "10.38.2.81"
