- name: Gestionar creación de zonas en Brocade G720
  hosts: brocade_switches
  gather_facts: no
  vars_files:
    - zones.yml 
    # Formato del archiovo de zonas
    # zones:
    #  - name:   AIX72_ORCLX_DESA_v1_fcs4_V7200    
    #    members:   
    #      - AIX72_ORCLX_DESA_v1_fcs4      
    #      - V7200CONTI_N1_P2      
    #      - V7200CONTI_N2_P1               
    #  - name:   AIX72_ORCLX_DESA_v1_fcs4_V9000   
    #    members:   
    #      - AIX72_ORCLX_DESA_v1_fcs4      
    #      - SVC_V9000_N1_PORT_7_2      
    #      - SVC_V9000_N2_PORT_7_2      
    #      - SVC_V9000Conti_N1_PORT_3_3      
    #      -  SVC_V9000Conti_N1_PORT_4_4   
  
  tasks:
    - name: Obtener lista de zonas existentes en el switch
      raw: zoneshow
      register: zones_actuales_raw

    - name: Extraer nombres de zonas configuradas
      set_fact:
        zonas_actuales: "{{ zones_actuales_raw.stdout_lines | map('regex_search', '^zone: (.+)$') | select('string') | list }}"

    - name: Eliminar duplicados en la lista de entrada
      set_fact:
        zones_unicas: "{{ zones | unique(attribute='name') }}"

    - name: Filtrar solo zonas no existentes
      set_fact:
        zonas_a_crear: "{{ zones_unicas | rejectattr('name', 'in', zonas_actuales) | list }}"

    - name: Mostrar zonas a crear
      debug:
        var: zonas_a_crear

    - name: Crear zonas que no existen
      ansible.builtin.include_playbook:
        file: crear_zona.yml
      loop: "{{ zonas_a_crear }}"
      loop_control:
        loop_var: zona
      vars:
        zona_nombre: "{{ zona.name }}"
        zona_miembros: "{{ zona.members }}"
